### ISSUE TITLE
Mouse Position in Entitie List 

### ISSUE THREAD

**Issue by TaylorAvila** [diogoftp/ragnarok-pybot#8]
When I was looking at the entities, I could see that in addition to the coordinate on the map, the relative coordinate of the screen is also loaded. Wouldn't it be easier to use it to position the mouse?
Another idea would be to use a fake hid like ddxoft to operate on a server with gepard. I don't have much knowledge in python, but I started writing something in C.

**Comment by mustainiac** [comment]
send ur discord, please, we can talk about this

**Comment by TaylorAvila** [comment]
__codeplay

**Comment by oqhadev** [comment]
actualy in action/fight.py 
to click mob, already using screen cords, intead game cords

**Comment by TaylorAvila** [comment]
I could see later, I'm not using this code, I'm using my own code in C#, gepard here was detecting the use of python so I thought it would be better to rewrite it in C#
